apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: curryware-postgres-pvc
  labels:
    app: curryware-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
