apiVersion: v1
kind: PersistentVolume
metadata:
  name: curryware-postgres-pv-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Delete
  # This path was created manually.  Don't know if it has to exist prior to deployment.
  local:
    path: /var/curryware-db
  # In the real world (more that a single node) you build this type of storage for nodes to be
  # able to share this location.  It is required for this spec 
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - ubuntu-microk8s
