apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curryware-front-end
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "curryware-front-end"
    tags.datadoghq.com/version: "64"
  name: curryware-front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curryware-front-end
  template:
    metadata:
      labels:
        app: curryware-front-end
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "curryware-front-end"
        tags.datadoghq.com/version: "64"
      annotations:
        admission.datadoghq.com/python-lib.version: v2.18.1
    spec:
      containers:
        - name: curryware-front-end
          image: scotcurry4/curryware-front-end:64
          env:
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_APPSEC_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
          - name: DD_GIT_REPOSITORY_URL
            value: "github.com/scotcurry/front-end"
          - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
            value: "true"
          - name: DD_TRACE_DEBUG
            value: "false"
          - name: DD_TRACE_LOG_FILE
            value: ddtrace_logs.log
