apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curryware-java
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "curryware-java"
    tags.datadoghq.com/version: "14"
  name: curryware-java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curryware-java
  template:
    metadata:
      labels:
        app: curryware-java
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "curryware-java"
        tags.datadoghq.com/version: "14"
        # admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: curryware-java
          image: scotcurry4/curryware-java:14
          env:
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_APPSEC_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
          - name: DD_GIT_REPOSITORY_URL
            value: "github.com/scotcurry/curryware-java"
