apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curryware-yahoo-api
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "curryware-curryware-api"
    tags.datadoghq.com/version: "86"
  name: curryware-yahoo-api
  # See logging https://docs.datadoghq.com/containers/kubernetes/log/?tab=datadogoperator#example-log-autodiscovery-annotations
  annotations:
    ad.datadoghq.com/curryware-yahoo-api.logs: |
      [{
        "type": "file",
        "path": "/app/logs/yahoo-api.log",
        "service": "curryware-yahoo-api",
        "source": "csharp"
      }]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curryware-yahoo-api
  template:
    metadata:
      labels:
        app: curryware-yahoo-api
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "curryware-yahoo-api"
        tags.datadoghq.com/version: "86"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: v3.7.0
        ad.datadoghq.com/tags: '{"kafka": "producer"}'
    spec:
      containers:
        - name: curryware-front-end
          image: scotcurry4/curryware-yahoo-api:86
          ports: 
            - containerPort: 8087
          env:
          - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
            value: "true"
          - name: DD_APPSEC_ENABLED
            value: "true"
          - name: DD_IAST_ENABLED
            value: "true"
          - name: DD_APPSEC_SCA_ENABLED
            value: "true"  
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
          - name: KAFKA_BOOTSTRAP_SERVER
            value: "kafka.curryware.org:9092"
          - name: DD_DATA_STREAMS_ENABLED
            value: "true"
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: curryware-postgres-secrets
                key: postgres-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: curryware-postgres-secrets
                key: postgres-password
          - name: POSTGRES_DATABASE
            value: currywarefantasy
          - name: POSTGRES_SERVER
            value: "postgres.curryware.org"
          - name: POSTGRES_PORT
            value: "5432"
      # To understand how tracing works, you need to read (tracing library is right above this link) 
      # https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/single-step-apm/?tab=kubernetespreview
          ## All of these variables are commented out if using auto-injection.
          # - name: CORECLR_ENABLE_PROFILING
          #   value: "1"
          # - name: CORECLR_PROFILER
          #   value: "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
          # - name: CORECLR_PROFILER_PATH
          #   value: "/opt/datadog/Datadog.Trace.ClrProfiler.Native.so"
          # - name: DD_DOTNET_TRACER_HOME
          #   value: "/opt/datadog"
          # - name: LD_PRELOAD
          #   value: "/opt/datadog/continuousprofiler/Datadog.Linux.ApiWrapper.x64.so"
          # - name: DD_PROFILING_ENABLED
          #   value: "true"
