apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: curryware-nginx-ingress-controller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingresss.class: "nginx"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ubuntu-microk8s.curryware.org
      secretName: ingress-tls
  rules:
    - host: ubuntu-microk8s.curryware.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: curryware-front-end
                port:
                  number: 80
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: curryware-front-end
                port:
                  number: 80
