apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curryware-java-api-server
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "curryware-java-api-server"
    tags.datadoghq.com/version: "7"
  name: curryware-java-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curryware-java-api-server
  template:
    metadata:
      labels:
        app: curryware-java-api-server
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "curryware-java-api-server"
        tags.datadoghq.com/version: "7"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.47.3
        ad.datadoghq.com/tags: '{"java": "front-end-api-server"}'
    spec:
      containers:
        - name: curryware-java-api-server
          image: scotcurry4/curryware-java-api-server:7
          ports: 
            - containerPort: 8080
          env:
          - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
            value: "true"
          - name: DD_APPSEC_ENABLED
            value: "true"
          - name: DD_IAST_ENABLED
            value: "true"
          - name: DD_APPSEC_SCA_ENABLED
            value: "true"  
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: curryware-postgres-secrets
                key: postgres-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: curryware-postgres-secrets
                key: postgres-password
          - name: POSTGRES_DATABASE
            value: currywarefantasy
          - name: POSTGRES_SERVER
            value: "postgres.curryware.org"
          - name: POSTGRES_PORT
            value: "5432"
