apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curryware-yahoo-api
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "curryware-curryware-api"
    tags.datadoghq.com/version: "45"
  name: curryware-yahoo-api
  # See logging https://docs.datadoghq.com/containers/kubernetes/log/?tab=datadogoperator#example-log-autodiscovery-annotations
  ad.datadoghq.com/curryware-yahoo-api.logs: |
    [{
      "type": "file",
      "path": "/app/logs/yahoo-api.log"
      "service": "curryware-yahoo.api"
      "source": "csharp""
    }]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curryware-yahoo-api
  template:
    metadata:
      labels:
        app: curryware-yahoo-api
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: "curryware-yahoo-api"
        tags.datadoghq.com/version: "45"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: v3.4.0
    spec:
      containers:
        - name: curryware-front-end
          image: scotcurry4/curryware-yahoo-api:45
          env:
          - name: DD_APPSEC_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
          - name: DD_GIT_REPOSITORY_URL
            value: "github.com/scotcurry/curryware-yahoo-api"
          - name: KAFKA_BOOTSTRAP_SERVER
            value: "ubuntu-postgres.curryware.org:9092"
          ## All of these variables are commented out because we aree using auto-injection.
          
          # - name: CORECLR_ENABLE_PROFILING
          #   value: "1"
          # # - name: CORECLR_PROFILER
          #   value: "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
          # - name: CORECLR_PROFILER_PATH
          #   value: "/opt/datadog/Datadog.Trace.ClrProfiler.Native.so"
          # - name: DD_DOTNET_TRACER_HOME
          #   value: "/opt/datadog"
          # - name: LD_PRELOAD
          #   value: "/opt/datadog/continuousprofiler/Datadog.Linux.ApiWrapper.x64.so"
          # - name: DD_PROFILING_ENABLED
          #   value: "true"
