apiVersion: v1
kind: Service
metadata:
  labels:
    app: curryware-firebase-auth
  name: curryware-firebase-auth
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: curryware-firebase-auth
  type: NodePort
