apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-secret-tls
  dnsNames:
    - ubuntu-microk8s.curryware.org
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
