# Github example: https://github.com/DataDog/datadog-operator/blob/main/examples/datadogagent/v2alpha1/datadog-agent-all.yaml
kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  global:
    clusterName: curryware-k8s
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    nodeLabelsAsTags:
      org.opencontainers.image.revision: DD_GIT_COMMIT_SHA
    logLevel: info
    kubelet:
      tlsVerify: false
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
  features:
    apm:
    #   enabled: true
      instrumentation:
        enabled: true
        libVersions:
          java: "1"
          python: "2"
          dotnet: "3"
        enabledNamespaces:
          - default
          - curryware
          - postgres
    admissionController:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
    npm:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    orchestratorExplorer:
      enabled: true
    liveProcessCollection:
      enabled: true
    remoteConfiguration:
      enabled: true
    liveContainerCollection:
      enabled: true
    cws:
      enabled: true
    cspm:
      enabled: true
      hostBenchmarks:
        enabled: true
