# Github example: https://github.com/DataDog/datadog-operator/blob/main/examples/datadogagent/v2alpha1/datadog-agent-all.yaml
kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  global:
    clusterName: curryware-k8s
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    nodeLabelsAsTags:
      org.opencontainers.image.revision: DD_GIT_COMMIT_SHA
    logLevel: info
    kubelet:
      tlsVerify: false
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
      containers:
        agent:
          env:
            - name: DD_IGNORE_AUTOCONF
              value: "redisdb"
            - name: DD_OBSERVABILITY_PIPELINES_WORKER_LOGS_ENABLED
              value: "true"
            - name: DD_OBSERVABILITY_PIPELINES_WORKER_LOGS_URL
              value: "http://opworker.curryware.org:8282"
        trace-agent:
          env:
            - name: DD_LOG_LEVEL
              value: "debug"
  clusterAgent:
  features:
    apm:
      enabled: true
      instrumentation:
        enabled: true
        enabledNamespaces:
          - default
          - curryware
    admissionController:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
    npm:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    orchestratorExplorer:
      enabled: true
    liveProcessCollection:
      enabled: true
    remoteConfiguration:
      enabled: true
    liveContainerCollection:
      enabled: true
    cws:
      enabled: true
    cspm:
      enabled: true
      hostBenchmarks:
        enabled: true
    sbom:
      containerImage:
        enabled: true
      host:
        enabled: true