# This information is based on this file https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml
targetSystem: "linux"
datadog:
    clusterName: minikube
    apiKeyExistingSecret: datadog-secrets
    appKeyExistingSecret: datadog-secrets
    # GKE does not accept dots (.), so default to not using them.
    loglevel: debug
    kubelet:
      tlsVerify:  false

    apm:
      portEnabled: true

    admissionController:
      enabled: true
      mutatedUnlabelled: true

    logs:
      enabled: true
      containerCollectAll: true

    processAgent:
      enabled: true
      processCollection: true
      processDiscovery: true
    networkMonitoring:
      enabled: true
    serviceMonitoring:
      enabled: true
    remoteConfiguration:
      enabled: true